### ISSUE TITLE
Repo Org Suggestions

### ISSUE THREAD

**Issue by TomDonoghue** [LuyandaMdanda/TUH_EEG-MNE#1]
Suggestions to keep the repo clean & organized:
- Add a README! This can be super simple, but helps briefly describe what's here. 
- Separate out some things: I would recommend adding a 'data', 'notebooks', and 'scripts' folder, and moving items into each one, as makes sense. It makes it much easier to find things, especially as the project grows. You might also choose a slightly different organization (you can see examples of having those 3 folders in some of my repos).

**Comment by LuyandaMdanda** [comment]
Completed
